#!/bin/bash
set -e

mysql --protocol=socket -uroot -p$MYSQL_ROOT_PASSWORD <<EOSQL
CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS';
GRANT SELECT ON $DB_DATABASE.* TO '$DB_USER'@'%';

CREATE USER '$DB_USER_MODIFY'@'%' IDENTIFIED BY '$DB_PASS_MODIFY';
GRANT SELECT, INSERT, UPDATE ON $DB_DATABASE.* TO '$DB_USER_MODIFY'@'%';

CREATE USER '$DB_USER_DELETE'@'%' IDENTIFIED BY '$DB_PASS_DELETE';
GRANT SELECT, INSERT, UPDATE, DELETE ON $DB_DATABASE.* TO '$DB_USER_DELETE'@'%';
EOSQL